version: '3.7'

services:
  node:
    container_name: planner-node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app:delegated
      - /app/node_modules
