version: '3.7'

services:
  php-fpm:
    container_name: planner-php-fpm
    build:
      context: ./docker/php-fpm
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - db
    volumes:
      - .:/var/www:delegated
    networks:
      - plannerapp

  nginx:
    image: nginx:stable-alpine
    container_name: planner-nginx
    ports:
      - 80:80
    depends_on:
      - php-fpm
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - plannerapp

  db:
    image: mysql:8.0
    container_name: planner-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - plannerapp

networks:
  plannerapp:

volumes:
  db: